### ISSUE TITLE
Create a checkpoint to save the data submission state

### ISSUE THREAD

**Issue by johan-rocha** [unb-mds/2024-1-EducaMinas-backend#42]
## Description
When sending data from csv files, a network, software or database connection failure may occur. This problem focuses on recording the sending state so that there is consistency in the data.

## Tasks
- [ ] Create checkpoint saving function
- [ ] Create checkpoint loading function
- [ ] Ensure replacement of saved reading logs

## Tests / Evaluation
- [ ] perform performance tests
- [ ] do consistency tests

## Responsible Parties
@johan-rocha
