### ISSUE TITLE
Adapt ETL from registrations to indicators

### ISSUE THREAD

**Issue by johan-rocha** [unb-mds/2024-1-EducaMinas-backend#44]
## Description
Generalize the analysis of data extracted from enrollments for indicators through classes

## Tasks
- [x] generalization of similar data between 'matricula' and 'indicador' with compatible classes
- [x] processing of specific formatting data

## Tests / Evaluation
- [ ] unitary performance test between 'matricula' and 'indicador'

## Responsible Parties
@johan-rocha
